display_errors=Off
log_errors=On
memory_limit=512M
max_execution_time=180
max_input_time=180
post_max_size=20M
upload_max_filesize=16M
session.cookie_httponly=1
session.cookie_samesite=Lax
opcache.enable=1
opcache.validate_timestamps=0
